### PR TITLE
C++ example

### PR DESCRIPTION
**Pull request by chethanapavan**
@lorensen @ajpmaclean Please review.

### CODE REVIEW

**Comment by ajpmaclean** [comment]
It looks good, however in `Boolean.cxx`:
1) For me the name `Boolean` is not really descriptive. Maybe it should be called `BooleanOperationImplicitFunctions` and go in under the menu entry `Working With 3D Data` however the code should stay in `Cxx/ImplicitFunctions`. 
2) The formatting should be 2 spaces not 4.
3) The blank line after `int main(int argc, char *argv[])`should be removed.
4) I would suggest replacing  VTK variable declarations (`vtkSmartPointer<vtkXX>`)  with  `auto vtkXX`.

e.g Change the VTK variable declarations in this fashion throughout your code:
```C++
  vtkSmartPointer<vtkNamedColors> colors =
    vtkSmartPointer<vtkNamedColors>::New();
```
to
```C++
  auto colors =
    vtkSmartPointer<vtkNamedColors>::New();
```
What do you think @lorensen ?

**Comment by chethanapavan** [comment]
@ajpmaclean thank you for the response, required changes had done please verify.

**Comment by ajpmaclean** [comment]
1) You need to rename `src/Cxx/ImplicitFunctions/Boolean.cxx` to `src/Cxx/ImplicitFunctions/BooleanOperationImplicitFunctions.cxx`
2) `src/Testing/Baseline/Cxx/ImplicitFunctions/TestBooleanOperationImplicitFunctions.png` is missing, please add it in.

**Comment by chethanapavan** [comment]
@ajpmaclean I made required changes. Please review.

**Comment by ajpmaclean** [comment]
It looks really nice, thankyou for your efforts.

**Pull request merged**
