### PR TITLE
Add frustum

### PR DESCRIPTION
**Pull request by chakravarthi589**

### CODE REVIEW

**Comment by chakravarthi589** [comment]
@ajpmaclean : Is this fine Now?

**Comment by ajpmaclean** [comment]
You have conflicting files. Please resolve them. I have no idea of the relevance of the change to CMakeLists.txt in relation to this merge request.

**Comment by chakravarthi589** [comment]
I have removed the Conflicts Now. Please Check

**Comment by ajpmaclean** [comment]
Two issues:
1) Resizing the window doesn't resize the image, something seems to be missing here.
2) You are missing a test image, you can create it with code like this (remember to delete this code once the image is produced, also check that the image is the correct size):
```Java
import vtk.vtkPNGWriter;
import vtk.vtkWindowToImageFilter;

// ...
        renWin.GetRenderer().ResetCamera();

        vtkWindowToImageFilter windowToImageFilter = new vtkWindowToImageFilter();
        windowToImageFilter.SetInput(renWin.GetRenderWindow());
        // For some reason this has to be set to 2 to get a 400X400 image.
        windowToImageFilter.SetScale(2); // image quality
        windowToImageFilter.SetInputBufferTypeToRGB();
        windowToImageFilter.ReadFrontBufferOff();
        windowToImageFilter.Update();

        vtkPNGWriter writer = new vtkPNGWriter();
        writer.SetFileName("Frustum.png");
        writer.SetInputConnection(windowToImageFilter.GetOutputPort());
        writer.Write();
```
For some reason the image becomes detached from the window (not sure why) but the correct png is produced.

**Comment by chakravarthi589** [comment]
I have Created Test Image and have uploaded the same in src/Testing/Baseline/Java/GeometricObjects/TestFrustum.png

Which IDE are you using ? to check image resize problem. 
It works fine with eclipse IDE. Let me also check with the one you are working. 
testfrustum

**Pull request closed without merging**
