### PR TITLE
Updating procedure for load native libraries

### PR DESCRIPTION
**Pull request by adithyakoundinya**
The native libraries were not loading when the example programs were tried in eclipse. I have modified the procedure for loading, in almost all the examples.

### CODE REVIEW

**Comment by adithyakoundinya** [comment]
It is not tested on IntelliJ and Visual code. I will test it and get back to you.

**Comment by ajpmaclean** [comment]
Thankyou for offering to do this.

**Comment by ajpmaclean** [comment]
I can verify that this works in IntelliJ. So I will commit.

Thankyou for your contribution.

**Comment by adithyakoundinya** [comment]
Thank you for verifying on my behalf and merging it.

**Pull request merged**
