### PR TITLE
SampleFunction example in python.

### PR DESCRIPTION
**Pull request by pavankumarbn**

### CODE REVIEW

**Comment by ajpmaclean** [comment]
Please add a link in ˋsrc/Python.mdˋ in the section **Implicit Functions and Iso-surfaces** in alphabetic order. Please follow carefully the syntax in this file. I would copy the corresponding line in ˋsrc/Cxx.mdˋ and modify accordingly, the only change would be to change *Cxx* to *Python* once you copy the line. Be very careful with these files as they are used to generate the web pages.

**Comment by pavankumarbn** [comment]
@ajpmaclean Sure I will add.

**Comment by ajpmaclean** [comment]
Looks, good, one thing, can you please update,  using four spaces instead of two in `SampleFunction.py`.

All the Python code is using four spaces no tabs and a trailing blank line.

**Comment by pavankumarbn** [comment]
@ajpmaclean Sure I will update. Thank you.

**Comment by pavankumarbn** [comment]
@ajpmaclean I replaced with four spaces please review on the same.

**Comment by ajpmaclean** [comment]
Re: ˋSampleFunction.pyˋ, why did you add two spaces after the line ˋmain()ˋ?

**Comment by pavankumarbn** [comment]
@ajpmaclean Sorry, I have updated it.

**Comment by ajpmaclean** [comment]
Thanks

**Comment by pavankumarbn** [comment]
@ajpmaclean Thank you.

**Pull request merged**
