### PR TITLE
Add kochanek spline

### PR DESCRIPTION
**Pull request by chakravarthi589**

### CODE REVIEW

**Comment by chakravarthi589** [comment]
@ajpmaclean : : Please review.

**Comment by chakravarthi589** [comment]
@ajpmaclean : No .txt file. Indentation fixed. Please review.

**Comment by ajpmaclean** [comment]
@chakravarthi589

 **FYI:** You may come across situations where you need to create a color that is not in vtkNamedColors, look at [CylinderExample](https://lorensen.github.io/VTKExamples/site/Java/GeometricObjects/CylinderExample/) for one way of doing this.

**Comment by chakravarthi589** [comment]
@ajpmaclean : Thank you for the information.

**Pull request merged**
