### PR TITLE
Change some examples to handle future transparency changes

### PR DESCRIPTION
**Pull request by martinken**
Minor changes and an inprovement to Cutter.cxx

### CODE REVIEW

**Comment by martinken** [comment]
@lorensen Some minor changes

**Comment by lorensen** [comment]
Ken, Is ForceOpaque a new method? If do we should ifdef on the vtk version.
The examples should work on some older versions.
Bill

**Comment by martinken** [comment]
It was added Oct 2015. How far back do you go?

**Comment by lorensen** [comment]
That's plenty. I'll merge. Thanks

**Comment by martinken** [comment]
Thanks, I'll create a vtk topic to test the new hash and make sure it works on existing VTK.

**Pull request merged**
