### PR TITLE
Using CompositeMapper2's API to set block attributes.

### PR DESCRIPTION
**Pull request by alvarosan**
vtkCompositeDataDisplayAttributes now maps block attributes by vtkDataObject*.

### CODE REVIEW

**Comment by alvarosan** [comment]
This addresses the issue pointed out in #22 @lorensen

**Comment by martinken** [comment]
@lorensen can you rev the VTK version?

**Comment by lorensen** [comment]
I have a few more updates. I'll do it shortly once I'm sure my updates are
good...

On Sep 27, 2017 11:41 AM, "Ken Martin" <notifications@github.com> wrote:

@lorensen <https://github.com/lorensen> can you rev the VTK version?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/lorensen/VTKExamples/pull/23#issuecomment-332564029>,
or mute the thread

**Comment by alvarosan** [comment]
I opened an [mr](https://gitlab.kitware.com/vtk/vtk/merge_requests/3356) to bump  WikiExamples, should I bump it to the latest master to include your updates @lorensen ?

**Comment by lorensen** [comment]
No, I have a newer bump here:
https://gitlab.kitware.com/vtk/vtk/merge_requests/3355

**Comment by lorensen** [comment]
Sorry, misread your email. Yes, use the hash from my MR in your MR.
Then I can close my MR.

**Comment by alvarosan** [comment]
Ok

**Pull request merged**
