### PR TITLE
Add parametric objects

### PR DESCRIPTION
**Pull request by chakravarthi589**

### CODE REVIEW

**Comment by chakravarthi589** [comment]
@ajpmaclean : Please review.

**Comment by ajpmaclean** [comment]
Please check carefully, you have deleted TestParametricObjects.png, so you need to supply an updated image,

**Comment by chakravarthi589** [comment]
@ajpmaclean: Pardon me. I have added the updated image now.  please review

**Comment by ajpmaclean** [comment]
Thanks

**Pull request merged**
