### PR TITLE
Add text origin

### PR DESCRIPTION
**Pull request by chakravarthi589**

### CODE REVIEW

**Comment by chakravarthi589** [comment]
@ajpmaclean : Please Review.

**Comment by chakravarthi589** [comment]
@ajpmaclean : Please Review.

**Comment by ajpmaclean** [comment]
Missing TestTextOrigin.png

**Comment by chakravarthi589** [comment]
@ajpmaclean : Updated test image added. Please review.

**Comment by ajpmaclean** [comment]
Thankyou again.

**Pull request merged**
