### PR TITLE
Add convex point set

### PR DESCRIPTION
**Pull request by chakravarthi589**

### CODE REVIEW

**Comment by chakravarthi589** [comment]
@ajpmaclean : Thank you for your inputs. i'll get back with all the changes suggested.

**Comment by chakravarthi589** [comment]
@ajpmaclean: The Arrow1 example works fine. i'll rework for all the examples.

**Comment by ajpmaclean** [comment]
@chakravarthi589 Great, much appreciated.

**Comment by chakravarthi589** [comment]
@ajpmaclean : Please review the changes as suggested.

**Comment by ajpmaclean** [comment]
Looks good, thankyou.

**Pull request merged**
