### PR TITLE
Show how to color / scale glyphs with vtkGlyph3DMapper

### PR DESCRIPTION
**Pull request by estan**
Since the question seems to have been asked (unanswered) a few times [1] [2] [3] how to color / scale each glyph when using vtkGlyph3DMapper, and it took me some time to figure it out myself, I'm extending the example to show how to do it.

For the scaling, I chose to show the "by vector components" mode, where you can control the scaling along each axis independently.

I also repositioned the camera a little, and removed an old unused variable.

This is what the example looks like now:

testglyph3dmapper

Hope this is OK!

[1] http://vtk.1045678.n5.nabble.com/color-per-glyph-with-vtkGlyph3DMapper-td5722934.html
[2] http://vtk.1045678.n5.nabble.com/vtkGlyph3DMapper-wit-different-vector-for-position-scale-td5734758.html
[3] http://vtk.1045678.n5.nabble.com/Vtkglyph3dmapper-and-colors-transparency-td5732651.html

### CODE REVIEW

**Comment by estan** [comment]
What is the maximum line length in the coding style for the examples btw? I see that lines are broken quite early, should I have broken the `colors->InsertNextTypedTuple(namedColors->GetColor3ub("Red").GetData());` lines?

**Comment by ajpmaclean** [comment]
I use clang-format for formatting in C++ with the attached file. It uses LLVM as the base with a column limit of 80 which is probably best for rendering in HTML.

Here is the file: [clang-format.txt](https://github.com/lorensen/VTKExamples/files/1891989/clang-format.txt), remember to rename it to **.clang-format**. 

I then manually edit the `vtkSmartPointer` declarations  (when I remember!):
```
  vtkSmartPointer<vtkRenderer> ren = vtkSmartPointer<vtkRenderer>::New();
```
to
```
  vtkSmartPointer<vtkRenderer> ren =
    vtkSmartPointer<vtkRenderer>::New();
```

For Python I use the standard formatting on PyCharm.

**Comment by estan** [comment]
@ajpmaclean Do you think the additions are  okay?

**Comment by ajpmaclean** [comment]
Looks Ok to me.
@bill What do you think?

**Comment by lorensen** [comment]
Looks good, I'll merge.

**Comment by lorensen** [comment]
Thanks!

**Pull request merged**
