### PR TITLE
Add render view

### PR DESCRIPTION
**Pull request by chakravarthi589**

### CODE REVIEW

**Comment by chakravarthi589** [comment]
@ajpmaclean : Please review.
@lorensen : Am using two spaces instead of a tab space in all my examples. Please check the correctness.

**Comment by chakravarthi589** [comment]
@ajpmaclean : Test image is provided for this. Anything else required?

**Comment by chakravarthi589** [comment]
@ajpmaclean : have updated description in md file.

**Comment by ajpmaclean** [comment]
Thanks

**Pull request merged**
