### PR TITLE
add option to not run a test fix a test

### PR DESCRIPTION
**Pull request by martinken**
Fix a resize issue on one test, also add option to exclude a test
which still will compile the test, but not run it.

### CODE REVIEW

**Comment by martinken** [comment]
@lorensen   I fixed one test, and added an option to exclude tests. The option will still compile the test, to catch compile issues, but will not run them.  I dug into the issues a bit. The floating point I think requires a ctest change not sure. One test requires a data file which I could not find. The last test is crashing with a real issue that could be in the test code or in VTK. Not sure but for the buildbots it needs to be suppressed until someone can look at it and fix it.

**Comment by martinken** [comment]
@lorensen  Hey Bill want me to rev VTK to the latest Examples?

**Comment by lorensen** [comment]
@martinken Ken, I have a gitlab topic that does that. I'm waiting for the tests to run on mun.

**Comment by martinken** [comment]
Cool thanks!

**Pull request merged**
