### PR TITLE
Add glyph3D

### PR DESCRIPTION
**Pull request by chakravarthi589**
@ajpmaclean : Please review.

### CODE REVIEW

**Comment by ajpmaclean** [comment]
I suggest you delete the author/affiliation stuff in the markdown files, it is just visual clutter and is not usually done. The proper place for this will be in your profile. As you should know git automatically tracks contributors.

**Comment by chakravarthi589** [comment]
@ajpmaclean : Removed.

**Comment by ajpmaclean** [comment]
Thanks for deleting this, please do it for the rest of your contributions. I have been worrying about it as it is not usually done and anyway the tool **git blame** can be used to track who changed what files, lines in files and why.

**Comment by chakravarthi589** [comment]
@ajpmaclean :  There was no intended reason to add the author information in the md file.  I'll not include anymore.  Thank you.

**Comment by ajpmaclean** [comment]
Don't worry about the ones already committed, unless you are updating.

**Comment by chakravarthi589** [comment]
ya sure.

**Pull request merged**
